name: OpenWrt R4S

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "LICENSE", "**/README.md" ]
    tags: [ "v*" ]
jobs:
  imagebuilder:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        uses: tidylabs/action-openwrt-imagebuilder@main

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: openwrt-*-sysupgrade.img.gz

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: contains(github.ref, '-rc')
          files: openwrt-*-sysupgrade.img.gz
