name: OpenWrt R4S

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "LICENSE", "**/README.md" ]
    tags: [ "v*" ]
jobs:
  imagebuilder:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --pull always

    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y
          bzip2
          file
          gawk
          git
          make
          perl
          python3-distutils
          rsync
          unzip
          wget

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: ./build_image.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: openwrt-*-sysupgrade.img.gz

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: contains(github.ref, '-rc')
          files: openwrt-*-sysupgrade.img.gz
